DROP TABLE IF EXISTS `test`.`TB_CAR` ;
CREATE TABLE IF NOT EXISTS `test`.`TB_CAR` (
  `CAR_NO` VARCHAR(13) NOT NULL COMMENT '차량번호',
  `YEAR` VARCHAR(50) NULL DEFAULT NULL COMMENT '연식',
  `UPDATE_ID` VARCHAR(13) NULL DEFAULT NULL COMMENT '',
  `UPDATE_DT` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`CAR_NO`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

DROP TABLE IF EXISTS `test`.`TB_MEMBER` ;
CREATE TABLE IF NOT EXISTS `test`.`TB_MEMBER` (
  `MEMBER_NO` VARCHAR(13) NOT NULL COMMENT '회원번호',
  `NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '성명',
  `EMAIL` VARCHAR(50) NULL DEFAULT NULL COMMENT '이메일',
  `UPDATE_ID` VARCHAR(13) NULL DEFAULT NULL COMMENT '',
  `UPDATE_DT` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`MEMBER_NO`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


DROP TABLE IF EXISTS `test`.`TB_Organization` ;
CREATE TABLE IF NOT EXISTS `test`.`TB_Organization` (
  `ID` VARCHAR(50) NOT NULL COMMENT '아이디',
  `TEXT` VARCHAR(50) NULL DEFAULT NULL COMMENT '텍스트',
  `PARENT` VARCHAR(50) NULL DEFAULT NULL COMMENT '부모',
  `ICON` VARCHAR(50) NULL DEFAULT NULL COMMENT '아이콘',
  `STATE` VARCHAR(50) NULL DEFAULT NULL COMMENT '상태',
  `UPDATE_ID` VARCHAR(13) NULL DEFAULT NULL COMMENT '',
  `UPDATE_DT` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;



INSERT INTO `test`.`TB_Organization` (`ID`, `TEXT`, `PARENT`, `ICON`, `UPDATE_ID`, `UPDATE_DT`) VALUES ('root', 'root', '#', '', 'system', now());
INSERT INTO `test`.`TB_Organization` (`ID`, `TEXT`, `PARENT`, `ICON`, `UPDATE_ID`, `UPDATE_DT`) VALUES ('group1', 'group1', 'root', '', 'system', now());


