DROP TABLE IF EXISTS `test`.`TB_CAR` ;
CREATE TABLE IF NOT EXISTS `test`.`TB_CAR` (
  `CAR_NO` VARCHAR(13) NOT NULL COMMENT '차량번호',
  `YEAR` VARCHAR(50) NULL DEFAULT NULL COMMENT '연식',
  `UPDATE_ID` VARCHAR(13) NULL DEFAULT NULL COMMENT '',
  `UPDATE_DT` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`CAR_NO`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

DROP TABLE IF EXISTS `test`.`TB_MEMBER` ;
CREATE TABLE IF NOT EXISTS `test`.`TB_MEMBER` (
  `MEMBER_NO` VARCHAR(13) NOT NULL COMMENT '회원번호',
  `NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '성명',
  `EMAIL` VARCHAR(50) NULL DEFAULT NULL COMMENT '이메일',
  `UPDATE_ID` VARCHAR(13) NULL DEFAULT NULL COMMENT '',
  `UPDATE_DT` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`MEMBER_NO`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
